### ISSUE TITLE
[4.3.1] Can not access Media Archive

### ISSUE THREAD

**Issue by nalyk** [sourcefabric/Newscoop#931]
Upgraded to 4.3.1 and getting this error when accessing Media Archive (from prod.log)

```
[2015-01-12 11:38:55] request.CRITICAL: Uncaught PHP Exception Zend_Controller_Exception: "Entity was not found.#0 /var/lib/newscoop/library/Proxy/__CG__NewscoopImageRendition.php(98): Proxy\__CG__\Newscoop\Image\Rendition->__load() #1 /var/lib/newscoop/library/Newscoop/Package/Item.php(144): Proxy\__CG__\Newscoop\Image\Rendition->setCoords(NULL) #2 /var/lib/newscoop/application/modules/admin/views/helpers/SlideshowsJson.php(28): Newscoop\Package\Item->getRendition() #3 [internal function]: Admin_View_Helper_SlideshowsJson->{closure}(Object(Newscoop\Package\Item)) #4 /var/lib/newscoop/application/modules/admin/views/helpers/SlideshowsJson.php(30): array_map(Object(Closure), Array) #5 [internal function]: Admin_View_Helper_SlideshowsJson->{closure}(Object(Newscoop\Package\Package)) #6 /var/lib/newscoop/application/modules/admin/views/helpers/SlideshowsJson.php(32): array_map(Object(Closure), Array) #7 [internal function]: Admin_View_Helper_SlideshowsJson->SlideshowsJson(Array) #8 /var/lib/newscoop/vendor/bombayworks/zendframework1/library/Zend/View/Abstract.php(350): call_user_func_array(Array, Array) #9 /var/lib/newscoop/admin-files/media-archive/index.php(52): Zend_View_Abstract->__call('slideshowsJson', Array) #10 /var/lib/newscoop/admin-files/media-archive/index.php(52): Zend_View->slideshowsJson(Array) #11 /var/lib/newscoop/application/modules/admin/controllers/LegacyController.php(129): require_once('/var/lib/newsco...') #12 /var/lib/newscoop/vendor/bombayworks/zendframework1/library/Zend/Controller/Action.php(516): Admin_LegacyController->indexAction() #13 /var/lib/newscoop/vendor/bombayworks/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('indexAction') #14 /var/lib/newscoop/vendor/bombayworks/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http)) #15 /var/lib/newscoop/src/Newscoop/ZendBridgeBundle/Controller/BridgeController.php(56): Zend_Controller_Front->dispatch() #16 [internal function]: Newscoop\ZendBridgeBundle\Controller\BridgeController->indexAction(Object(Symfony\Component\HttpFoundation\Request)) #17 /var/lib/newscoop/application/bootstrap.php.cache(2891): call_user_func_array(Array, Array) #18 /var/lib/newscoop/application/bootstrap.php.cache(2865): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #19 /var/lib/newscoop/application/bootstrap.php.cache(2994): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #20 /var/lib/newscoop/application/bootstrap.php.cache(2274): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #21 /var/lib/newscoop/public/index.php(69): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #22 /var/lib/newscoop/index.php(17): require_once('/var/lib/newsco...') #23 /var/lib/newscoop/admin.php(2): require_once('/var/lib/newsco...') #24 {main}" at /var/lib/newscoop/vendor/bombayworks/zendframework1/library/Zend/Controller/Plugin/Broker.php line 336 {"exception":"[object] (Zend_Controller_Exception: Entity was not found.#0 /var/lib/newscoop/library/Proxy/__CG__NewscoopImageRendition.php(98): Proxy\\__CG__\\Newscoop\\Image\\Rendition->__load()\n#1 /var/lib/newscoop/library/Newscoop/Package/Item.php(144): Proxy\\__CG__\\Newscoop\\Image\\Rendition->setCoords(NULL)\n#2 /var/lib/newscoop/application/modules/admin/views/helpers/SlideshowsJson.php(28): Newscoop\\Package\\Item->getRendition()\n#3 [internal function]: Admin_View_Helper_SlideshowsJson->{closure}(Object(Newscoop\\Package\\Item))\n#4 /var/lib/newscoop/application/modules/admin/views/helpers/SlideshowsJson.php(30): array_map(Object(Closure), Array)\n#5 [internal function]: Admin_View_Helper_SlideshowsJson->{closure}(Object(Newscoop\\Package\\Package))\n#6 /var/lib/newscoop/application/modules/admin/views/helpers/SlideshowsJson.php(32): array_map(Object(Closure), Array)\n#7 [internal function]: Admin_View_Helper_SlideshowsJson->SlideshowsJson(Array)\n#8 /var/lib/newscoop/vendor/bombayworks/zendframework1/library/Zend/View/Abstract.php(350): call_user_func_array(Array, Array)\n#9 /var/lib/newscoop/admin-files/media-archive/index.php(52): Zend_View_Abstract->__call('slideshowsJson', Array)\n#10 /var/lib/newscoop/admin-files/media-archive/index.php(52): Zend_View->slideshowsJson(Array)\n#11 /var/lib/newscoop/application/modules/admin/controllers/LegacyController.php(129): require_once('/var/lib/newsco...')\n#12 /var/lib/newscoop/vendor/bombayworks/zendframework1/library/Zend/Controller/Action.php(516): Admin_LegacyController->indexAction()\n#13 /var/lib/newscoop/vendor/bombayworks/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('indexAction')\n#14 /var/lib/newscoop/vendor/bombayworks/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))\n#15 /var/lib/newscoop/src/Newscoop/ZendBridgeBundle/Controller/BridgeController.php(56): Zend_Controller_Front->dispatch()\n#16 [internal function]: Newscoop\\ZendBridgeBundle\\Controller\\BridgeController->indexAction(Object(Symfony\\Component\\HttpFoundation\\Request))\n#17 /var/lib/newscoop/application/bootstrap.php.cache(2891): call_user_func_array(Array, Array)\n#18 /var/lib/newscoop/application/bootstrap.php.cache(2865): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#19 /var/lib/newscoop/application/bootstrap.php.cache(2994): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#20 /var/lib/newscoop/application/bootstrap.php.cache(2274): Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#21 /var/lib/newscoop/public/index.php(69): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#22 /var/lib/newscoop/index.php(17): require_once('/var/lib/newsco...')\n#23 /var/lib/newscoop/admin.php(2): require_once('/var/lib/newsco...')\n#24 {main} at /var/lib/newscoop/vendor/bombayworks/zendframework1/library/Zend/Controller/Plugin/Broker.php:336, Doctrine\\ORM\\EntityNotFoundException: Entity was not found. at /var/lib/newscoop/library/Proxy/__CG__NewscoopImageRendition.php:32)"} []
[2015-01-12 11:38:55] sentry.CRITICAL: Uncaught exception {"exception":"[object] (Zend_Controller_Exception: Entity was not found.#0 /var/lib/newscoop/library/Proxy/__CG__NewscoopImageRendition.php(98): Proxy\\__CG__\\Newscoop\\Image\\Rendition->__load()\n#1 /var/lib/newscoop/library/Newscoop/Package/Item.php(144): Proxy\\__CG__\\Newscoop\\Image\\Rendition->setCoords(NULL)\n#2 /var/lib/newscoop/application/modules/admin/views/helpers/SlideshowsJson.php(28): Newscoop\\Package\\Item->getRendition()\n#3 [internal function]: Admin_View_Helper_SlideshowsJson->{closure}(Object(Newscoop\\Package\\Item))\n#4 /var/lib/newscoop/application/modules/admin/views/helpers/SlideshowsJson.php(30): array_map(Object(Closure), Array)\n#5 [internal function]: Admin_View_Helper_SlideshowsJson->{closure}(Object(Newscoop\\Package\\Package))\n#6 /var/lib/newscoop/application/modules/admin/views/helpers/SlideshowsJson.php(32): array_map(Object(Closure), Array)\n#7 [internal function]: Admin_View_Helper_SlideshowsJson->SlideshowsJson(Array)\n#8 /var/lib/newscoop/vendor/bombayworks/zendframework1/library/Zend/View/Abstract.php(350): call_user_func_array(Array, Array)\n#9 /var/lib/newscoop/admin-files/media-archive/index.php(52): Zend_View_Abstract->__call('slideshowsJson', Array)\n#10 /var/lib/newscoop/admin-files/media-archive/index.php(52): Zend_View->slideshowsJson(Array)\n#11 /var/lib/newscoop/application/modules/admin/controllers/LegacyController.php(129): require_once('/var/lib/newsco...')\n#12 /var/lib/newscoop/vendor/bombayworks/zendframework1/library/Zend/Controller/Action.php(516): Admin_LegacyController->indexAction()\n#13 /var/lib/newscoop/vendor/bombayworks/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('indexAction')\n#14 /var/lib/newscoop/vendor/bombayworks/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))\n#15 /var/lib/newscoop/src/Newscoop/ZendBridgeBundle/Controller/BridgeController.php(56): Zend_Controller_Front->dispatch()\n#16 [internal function]: Newscoop\\ZendBridgeBundle\\Controller\\BridgeController->indexAction(Object(Symfony\\Component\\HttpFoundation\\Request))\n#17 /var/lib/newscoop/application/bootstrap.php.cache(2891): call_user_func_array(Array, Array)\n#18 /var/lib/newscoop/application/bootstrap.php.cache(2865): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#19 /var/lib/newscoop/application/bootstrap.php.cache(2994): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#20 /var/lib/newscoop/application/bootstrap.php.cache(2274): Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#21 /var/lib/newscoop/public/index.php(69): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#22 /var/lib/newscoop/index.php(17): require_once('/var/lib/newsco...')\n#23 /var/lib/newscoop/admin.php(2): require_once('/var/lib/newsco...')\n#24 {main} at /var/lib/newscoop/vendor/bombayworks/zendframework1/library/Zend/Controller/Plugin/Broker.php:336, Doctrine\\ORM\\EntityNotFoundException: Entity was not found. at /var/lib/newscoop/library/Proxy/__CG__NewscoopImageRendition.php:32)"} []
[2015-01-12 11:38:56] request.CRITICAL: Exception thrown when handling an exception (InvalidArgumentException: Template name "" is not valid (format is "bundle:section:template.format.engine").) {"exception":"[object] (Zend_Controller_Exception: Entity was not found.#0 /var/lib/newscoop/library/Proxy/__CG__NewscoopImageRendition.php(98): Proxy\\__CG__\\Newscoop\\Image\\Rendition->__load()\n#1 /var/lib/newscoop/library/Newscoop/Package/Item.php(144): Proxy\\__CG__\\Newscoop\\Image\\Rendition->setCoords(NULL)\n#2 /var/lib/newscoop/application/modules/admin/views/helpers/SlideshowsJson.php(28): Newscoop\\Package\\Item->getRendition()\n#3 [internal function]: Admin_View_Helper_SlideshowsJson->{closure}(Object(Newscoop\\Package\\Item))\n#4 /var/lib/newscoop/application/modules/admin/views/helpers/SlideshowsJson.php(30): array_map(Object(Closure), Array)\n#5 [internal function]: Admin_View_Helper_SlideshowsJson->{closure}(Object(Newscoop\\Package\\Package))\n#6 /var/lib/newscoop/application/modules/admin/views/helpers/SlideshowsJson.php(32): array_map(Object(Closure), Array)\n#7 [internal function]: Admin_View_Helper_SlideshowsJson->SlideshowsJson(Array)\n#8 /var/lib/newscoop/vendor/bombayworks/zendframework1/library/Zend/View/Abstract.php(350): call_user_func_array(Array, Array)\n#9 /var/lib/newscoop/admin-files/media-archive/index.php(52): Zend_View_Abstract->__call('slideshowsJson', Array)\n#10 /var/lib/newscoop/admin-files/media-archive/index.php(52): Zend_View->slideshowsJson(Array)\n#11 /var/lib/newscoop/application/modules/admin/controllers/LegacyController.php(129): require_once('/var/lib/newsco...')\n#12 /var/lib/newscoop/vendor/bombayworks/zendframework1/library/Zend/Controller/Action.php(516): Admin_LegacyController->indexAction()\n#13 /var/lib/newscoop/vendor/bombayworks/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('indexAction')\n#14 /var/lib/newscoop/vendor/bombayworks/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))\n#15 /var/lib/newscoop/src/Newscoop/ZendBridgeBundle/Controller/BridgeController.php(56): Zend_Controller_Front->dispatch()\n#16 [internal function]: Newscoop\\ZendBridgeBundle\\Controller\\BridgeController->indexAction(Object(Symfony\\Component\\HttpFoundation\\Request))\n#17 /var/lib/newscoop/application/bootstrap.php.cache(2891): call_user_func_array(Array, Array)\n#18 /var/lib/newscoop/application/bootstrap.php.cache(2865): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#19 /var/lib/newscoop/application/bootstrap.php.cache(2994): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#20 /var/lib/newscoop/application/bootstrap.php.cache(2274): Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#21 /var/lib/newscoop/public/index.php(69): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#22 /var/lib/newscoop/index.php(17): require_once('/var/lib/newsco...')\n#23 /var/lib/newscoop/admin.php(2): require_once('/var/lib/newsco...')\n#24 {main} at /var/lib/newscoop/vendor/bombayworks/zendframework1/library/Zend/Controller/Plugin/Broker.php:336, Doctrine\\ORM\\EntityNotFoundException: Entity was not found. at /var/lib/newscoop/library/Proxy/__CG__NewscoopImageRendition.php:32)"} []
[2015-01-12 11:38:56] sentry.ERROR: Uncaught Exception Zend_Controller_Exception: "Entity was not found.#0 /var/lib/newscoop/library/Proxy/__CG__NewscoopImageRendition.php(98): Proxy\__CG__\Newscoop\Image\Rendition->__load() #1 /var/lib/newscoop/library/Newscoop/Package/Item.php(144): Proxy\__CG__\Newscoop\Image\Rendition->setCoords(NULL) #2 /var/lib/newscoop/application/modules/admin/views/helpers/SlideshowsJson.php(28): Newscoop\Package\Item->getRendition() #3 [internal function]: Admin_View_Helper_SlideshowsJson->{closure}(Object(Newscoop\Package\Item)) #4 /var/lib/newscoop/application/modules/admin/views/helpers/SlideshowsJson.php(30): array_map(Object(Closure), Array) #5 [internal function]: Admin_View_Helper_SlideshowsJson->{closure}(Object(Newscoop\Package\Package)) #6 /var/lib/newscoop/application/modules/admin/views/helpers/SlideshowsJson.php(32): array_map(Object(Closure), Array) #7 [internal function]: Admin_View_Helper_SlideshowsJson->SlideshowsJson(Array) #8 /var/lib/newscoop/vendor/bombayworks/zendframework1/library/Zend/View/Abstract.php(350): call_user_func_array(Array, Array) #9 /var/lib/newscoop/admin-files/media-archive/index.php(52): Zend_View_Abstract->__call('slideshowsJson', Array) #10 /var/lib/newscoop/admin-files/media-archive/index.php(52): Zend_View->slideshowsJson(Array) #11 /var/lib/newscoop/application/modules/admin/controllers/LegacyController.php(129): require_once('/var/lib/newsco...') #12 /var/lib/newscoop/vendor/bombayworks/zendframework1/library/Zend/Controller/Action.php(516): Admin_LegacyController->indexAction() #13 /var/lib/newscoop/vendor/bombayworks/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('indexAction') #14 /var/lib/newscoop/vendor/bombayworks/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http)) #15 /var/lib/newscoop/src/Newscoop/ZendBridgeBundle/Controller/BridgeController.php(56): Zend_Controller_Front->dispatch() #16 [internal function]: Newscoop\ZendBridgeBundle\Controller\BridgeController->indexAction(Object(Symfony\Component\HttpFoundation\Request)) #17 /var/lib/newscoop/application/bootstrap.php.cache(2891): call_user_func_array(Array, Array) #18 /var/lib/newscoop/application/bootstrap.php.cache(2865): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #19 /var/lib/newscoop/application/bootstrap.php.cache(2994): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #20 /var/lib/newscoop/application/bootstrap.php.cache(2274): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #21 /var/lib/newscoop/public/index.php(69): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #22 /var/lib/newscoop/index.php(17): require_once('/var/lib/newsco...') #23 /var/lib/newscoop/admin.php(2): require_once('/var/lib/newsco...') #24 {main}" at /var/lib/newscoop/vendor/bombayworks/zendframework1/library/Zend/Controller/Plugin/Broker.php line 336 {"exception":"[object] (Zend_Controller_Exception: Entity was not found.#0 /var/lib/newscoop/library/Proxy/__CG__NewscoopImageRendition.php(98): Proxy\\__CG__\\Newscoop\\Image\\Rendition->__load()\n#1 /var/lib/newscoop/library/Newscoop/Package/Item.php(144): Proxy\\__CG__\\Newscoop\\Image\\Rendition->setCoords(NULL)\n#2 /var/lib/newscoop/application/modules/admin/views/helpers/SlideshowsJson.php(28): Newscoop\\Package\\Item->getRendition()\n#3 [internal function]: Admin_View_Helper_SlideshowsJson->{closure}(Object(Newscoop\\Package\\Item))\n#4 /var/lib/newscoop/application/modules/admin/views/helpers/SlideshowsJson.php(30): array_map(Object(Closure), Array)\n#5 [internal function]: Admin_View_Helper_SlideshowsJson->{closure}(Object(Newscoop\\Package\\Package))\n#6 /var/lib/newscoop/application/modules/admin/views/helpers/SlideshowsJson.php(32): array_map(Object(Closure), Array)\n#7 [internal function]: Admin_View_Helper_SlideshowsJson->SlideshowsJson(Array)\n#8 /var/lib/newscoop/vendor/bombayworks/zendframework1/library/Zend/View/Abstract.php(350): call_user_func_array(Array, Array)\n#9 /var/lib/newscoop/admin-files/media-archive/index.php(52): Zend_View_Abstract->__call('slideshowsJson', Array)\n#10 /var/lib/newscoop/admin-files/media-archive/index.php(52): Zend_View->slideshowsJson(Array)\n#11 /var/lib/newscoop/application/modules/admin/controllers/LegacyController.php(129): require_once('/var/lib/newsco...')\n#12 /var/lib/newscoop/vendor/bombayworks/zendframework1/library/Zend/Controller/Action.php(516): Admin_LegacyController->indexAction()\n#13 /var/lib/newscoop/vendor/bombayworks/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('indexAction')\n#14 /var/lib/newscoop/vendor/bombayworks/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))\n#15 /var/lib/newscoop/src/Newscoop/ZendBridgeBundle/Controller/BridgeController.php(56): Zend_Controller_Front->dispatch()\n#16 [internal function]: Newscoop\\ZendBridgeBundle\\Controller\\BridgeController->indexAction(Object(Symfony\\Component\\HttpFoundation\\Request))\n#17 /var/lib/newscoop/application/bootstrap.php.cache(2891): call_user_func_array(Array, Array)\n#18 /var/lib/newscoop/application/bootstrap.php.cache(2865): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#19 /var/lib/newscoop/application/bootstrap.php.cache(2994): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#20 /var/lib/newscoop/application/bootstrap.php.cache(2274): Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#21 /var/lib/newscoop/public/index.php(69): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#22 /var/lib/newscoop/index.php(17): require_once('/var/lib/newsco...')\n#23 /var/lib/newscoop/admin.php(2): require_once('/var/lib/newsco...')\n#24 {main} at /var/lib/newscoop/vendor/bombayworks/zendframework1/library/Zend/Controller/Plugin/Broker.php:336, Doctrine\\ORM\\EntityNotFoundException: Entity was not found. at /var/lib/newscoop/library/Proxy/__CG__NewscoopImageRendition.php:32)"} []
```

**Comment by takeit** [comment]
@nalyk have you tried to reload renditions in backend ? `Configure -> Image Renditions` and click `Reload`

**Comment by nalyk** [comment]
Yes, i have tried that, clearde cache, and tried again. Still a blank page.

**Comment by ahilles107** [comment]
hmmm... looks like after upgrade one of rendiotion used to generate slideshows is gone.

in your database table ``package`` you have field ``rendition``. Be sure that all used renditions are declared in theme.xml and visible (after reloading renditions) on ``admin/rendition`` page.
